//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone.Common.Medicare.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Capstone.Common.Medicare.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://proda.humanservices.gov.au.
        /// </summary>
        internal static string accessTokenAudience {
            get {
                return ResourceManager.GetString("accessTokenAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-www-form-urlencoded.
        /// </summary>
        internal static string AuthContentType {
            get {
                return ResourceManager.GetString("AuthContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vnd.proda.humanservices.gov.au/mga/sps/oauth/oauth20/token.
        /// </summary>
        internal static string AuthEndPoint {
            get {
                return ResourceManager.GetString("AuthEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://test.healthclaiming.api.humanservices.gov.au/claiming/ext-vnd.
        /// </summary>
        internal static string BaseURL {
            get {
                return ResourceManager.GetString("BaseURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://test.5.rsp.humanservices.gov.au/piaweb/api/b2b/v1/devices.
        /// </summary>
        internal static string DeviceActivationUrl {
            get {
                return ResourceManager.GetString("DeviceActivationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://test.5.rsp.humanservices.gov.au/piaweb/api/b2b/v1/orgs/{0}/devices/{1}/jwk.
        /// </summary>
        internal static string DeviceKeyRefreshUrl {
            get {
                return ResourceManager.GetString("DeviceKeyRefreshUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to urn:ietf:params:oauth:grant-type:jwt-bearer.
        /// </summary>
        internal static string GrantType {
            get {
                return ResourceManager.GetString("GrantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://medicareaustralia.gov.au/MCOL.
        /// </summary>
        internal static string MedicareTokenAudience {
            get {
                return ResourceManager.GetString("MedicareTokenAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ns.humanservices.gov.au/audit/type/proda/organisation.
        /// </summary>
        internal static string Proda_Audit_Type {
            get {
                return ResourceManager.GetString("Proda_Audit_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://ns.humanservices.gov.au/audit/type/proda/device.
        /// </summary>
        internal static string Proda_Subject_Type {
            get {
                return ResourceManager.GetString("Proda_Subject_Type", resourceCulture);
            }
        }
    }
}
